require('settings')
require('mappings')
require('lazy-config')
require('colorschemes-config.catppuccin')
require('nvim-treesitter-config')
require('nvim-tree-config')
require('lsp-config.lsp')
require('lsp-config.completions')
require('statusline-config.lualine')
require('telescope-config')
require('barbar-config')
require('run-config.code_runner')
require('run-config.debugger')
require('neoscroll-config')
require('terminal-config')
require('misc.todo-config')
require('misc.org')
require('misc.zoom')
require('greeter-config.alpha')
require('git-config.gitsigns')
-- require('minuet-ai-config')

